# Generated by Django 2.1.7 on 2019-04-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sluq',
            new_name='slug',
        ),
    ]
